[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
auto_sign_up = true
# 新しいユーザーを作成したときのデフォルトロールを「Viewer」に
default_role = Viewer
;header_property = username
;whitelist = 127.0.0.1
enable_login_token = false
trusted_ips = 127.0.0.1,10.0.0.0/8
